/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonParser;
import com.google.gson.stream.JsonReader;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.Reader;
import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test
    @DisplayName("Json Quotes file to object and print randomly")
    void fromJsonTest() throws FileNotFoundException {

        List <String> actualList = new ArrayList<>();
        List <String> excpList = new ArrayList<>();

        Gson gson = new Gson();
        Quotes quotes;

        Reader reader = new FileReader("C:\\Users\\Lenovo\\Desktop\\Advanced Java\\quotes\\quotes.json");
        JsonReader reader1 = new JsonReader(reader);
        JsonArray array = JsonParser.parseReader(reader1).getAsJsonArray();
        assertEquals(138,array.size());//To ensure read all json file
        quotes = gson.fromJson(array.get(10),Quotes.class);


        excpList.add("Chuck Klosterman");
        excpList.add("0 likes");
        excpList.add("It's easier to believe there's a monster under the bed if you've spent the last six months arguing with a monster.");

        actualList.add(quotes.author);
        actualList.add(quotes.likes);
        actualList.add(quotes.text);

        assertLinesMatch(excpList,actualList);
    }

}
